dist: trusty
sudo: required
services:
  - docker
before_install:
  - sudo /etc/init.d/postgresql stop
  - docker run -d -p 5432:5432 --name sqlg-testdb-postgres $(docker build -q sqlg-testdb-postgres/)
language: java
jdk:
  - oraclejdk8
#env:
#    - MAVEN_OPTS="-Xmx4096m"
#script: "./run-tests.sh"
script:
  - sudo rm /etc/mavenrc
  - export MAVEN_OPTS="-Djava.security.egd=file:/dev/./urandom -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmx5012m"
  - mvn -e -T40 test

notifications:
  email:
    recipients:
      - pieter.martin@riseup.net
    on_success: always
    on_failure: always
