dist: trusty
sudo: required
before_install:
  - sudo sed -i -e 's/max_connections.*/max_connections = 1000/' /etc/postgresql/9.6/main/postgresql.conf
  - sudo sed -i -e 's/#max_locks_per_transaction.*/max_locks_per_transaction = 256/' /etc/postgresql/9.6/main/postgresql.conf
  - sudo sed -i -e 's/#shared_buffers.*/shared_buffers = 1024MB/' /etc/postgresql/9.6/main/postgresql.conf
  - sudo /etc/init.d/postgresql restart
language: java
jdk:
  - oraclejdk8
#env:
#    - MAVEN_OPTS="-Xmx4096m"
#script: "./run-tests.sh"
script:
  - sudo rm /etc/mavenrc
  - export MAVEN_OPTS="-Xmx5012m"
  - mvn -e test
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database "sqlgraphdb";' -U postgres
  - psql -c 'create database "g1";' -U postgres
  - psql -c 'create database "g2";' -U postgres
  - psql -c 'create database "prototype";' -U postgres
  - psql -c 'create database "readGraph";' -U postgres
  - psql -c 'create database "standard";' -U postgres
  - psql -c 'create database "subgraph";' -U postgres
  - psql -c 'create database "temp";' -U postgres
  - psql -c 'create database "temp1";' -U postgres
  - psql -c 'create database "temp2";' -U postgres
  - psql -c 'create database "target";' -U postgres

notifications:
  email:
    recipients:
      - pieter.martin@riseup.net
    on_success: always
    on_failure: always
